In [1]:
import numpy as np

In [2]:
pollution_data = np.array([[45, 65, 70], [55, 60, 50], [60, 58, 67]])

most_polluted_day_index = np.argmax(pollution_data.mean(axis=1))

print(pollution_data[most_polluted_day_index])

[60 58 67]


In [3]:
forest_coverage = np.array([70, 80, 65, 90, 85])

total_forest_cover_lost = (100 - forest_coverage).sum() * 100

print(total_forest_cover_lost)

11000


In [4]:
water_quality = np.array([[7.8, 6.5, 8.0], [5.4, 7.2, 6.5]])

worst_water_quality_index = np.argmin(water_quality.mean(axis=1))

print(worst_water_quality_index)

1


In [5]:
animal_sightings = np.array([[5, 7, 8], [3, 4, 6], [9, 10, 7]])

highest_sightings_region_index = np.argmax(animal_sightings.mean(axis=1))

print(highest_sightings_region_index)

2


In [6]:
bird_sightings = np.array([3, 4, 2, 5, 1, 0, 4, 3, 5, 2, 1, 7, 8, 1, 2, 3, 4, 1, 0, 5, 6, 2, 3, 4, 1, 4, 6, 7])

reshaped_sightings = bird_sightings.reshape(4, 7)
total_sightings_per_week = reshaped_sightings.sum(axis=1)

print(total_sightings_per_week)

[19 27 21 27]


In [7]:
climate_data = np.array([[22, 50], [25, 43], [28, 35], [30, 20], [27, 25], [25, 30], [23, 40], [24, 55], [22, 60], [20, 65], [18, 70], [22, 58]])

transposed_climate_data = climate_data.transpose()
print(transposed_climate_data)

average_temperature = transposed_climate_data[0].mean()
average_precipitation = transposed_climate_data[1].mean()

print(average_temperature)
print(average_precipitation)

[[22 25 28 30 27 25 23 24 22 20 18 22]
 [50 43 35 20 25 30 40 55 60 65 70 58]]
23.833333333333332
45.916666666666664
